---
# tasks file for system

- name: Import task to install packages
  ansible.builtin.import_tasks: packages.yml

- name: Create and configure users
  ansible.builtin.import_tasks: users.yml

- name: Setup NFS mounts
  ansible.builtin.import_tasks: nfs.yml
  when: mount_nfs_shares

- name: Secure SSH settings
  vars:
    ssh_allow_users: "{{ user_account['name'] }}"
    sftp_enabled: true
  ansible.builtin.import_role:
    name: devsec.hardening.ssh_hardening

- name: Secure OS settings
  ansible.builtin.import_role:
    name: devsec.hardening.os_hardening
