---
# tasks file for system

- name: Install systemd mounts
  vars:
    description: "{{ item.name }}"
    what: "{{ item.server_path }}"
    where: "{{ item.mount_point }}"
  ansible.builtin.template:
    src: nfs.mount.j2
    dest: "/etc/systemd/system/{{ item.systemd_filename }}"
    mode: 0644
  loop: "{{ nfs_mounts }}"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Mount NFS shares
  ansible.builtin.systemd:
    name: "{{ item.mount_point }}"
    state: started
    enabled: yes
  loop: "{{ nfs_mounts }}"
