---
# tasks file for system

- name: Create local user
  ansible.builtin.user:
    name: "{{ user_account['name'] }}"
    shell: "{{ user_account['shell'] }}"
    groups: "{{ user_account['groups'] }}"
    password: "{{ user_account['password'] }}"
    update_password: on_create

- name: Add ssh key to authorized_keys
  ansible.posix.authorized_key:
    user: "{{ user_account['name'] }}"
    key: "{{ user_account['key'] }}"

- name: Copy in zshrc place-holder
  ansible.builtin.copy:
    dest: "/home/{{ user_account['name'] }}/.zshrc"
    content: "# TODO: install dotfiles"

- name: Install root dotfiles
  ansible.builtin.copy:
    src: root/
    dest: /root/
    mode: 0644
